### ISSUE TITLE
Question Regarding the PRCC Dataset Handling

### ISSUE THREAD

**Issue by Yxjjjjjj** [CroitoruAlin/dlcr#1]
I encountered an issue while attempting to reproduce your work. Specifically, I would like to know the directory structure of the prcc_processed and prcc datasets during training. When I try to run the code, I get an error related to key 116, which might be caused by a mismatch in the dataset's directory format.
Could you kindly provide more details on the directory structure or the steps involved in processing the datasets?

**Comment by CroitoruAlin** [comment]
Hello,

Thank you for pointing this out. 
In our experiments, we utilized a custom directory structure to each dataset while keeping the dataloaders unchanged. However, we organized the generated images into a uniform structure across all datasets when we shared them. As a result, some of the dataloaders are incompatible with this uniform structure.

To fix this issue for PRCC, we've just pushed a new dataloader that is capable of reading the images from this uniform structure.
